services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: mi-elasticsearch
    environment:
      - discovery.type=single-node   # run in dev mode, no cluster needed
      - xpack.security.enabled=false # turn off login for local demo
    ports:
      - "9200:9200"  # expose ES on localhost:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: mi-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch